### ISSUE TITLE
Feature: Support detailed running process management: save_steps, log_steps, eval_steps

### ISSUE THREAD

**Issue by catqaq** [OpenLLMAI/OpenRLHF#102]
I got a training collapse when saving models. so, 30 hours wasted.  
see:https://github.com/OpenLLMAI/OpenLLaMA2/issues/101

So, We need more detailed experimental process management. 
save_steps is ralated to https://github.com/OpenLLMAI/OpenLLaMA2/issues/65
log_steps, eval_steps are also necessary.

**Comment by catqaq** [comment]
讨论个问题，关于实验过程的精细化管理等功能，暂时有两个实现思路：
一是借助抱抱脸的trainer（功能丰富，也考虑到未来的扩展性和与HF生态的兼容性）
二是从头写（hf trainer封装的比较死，要支持PPO可能不太容易）
目前尝试了方案一，sft和RM的支持算是初步跑通了，不过PPO部分改起来可能不太容易。可能得先评估看看可行性，加上最近又支持了ray。

ps: 方案二的话TODO，主要没啥时间、也没啥动力从头写

**Comment by catqaq** [comment]
讨论结果：
尽量保持框架的精简性和可扩展性，不要使用Pytorch Lightning/HF trainer等高级封装

**Comment by catqaq** [comment]
预计本周内完成，由于ckpt会占用大量的硬盘空间，有些细节需要完善

**Comment by catqaq** [comment]
sft/rm/ppo support progress 2/3

**Comment by catqaq** [comment]
add basic ckpt function: f53571de43a4524644e75c9c472bbc69ac7b72c2

**Comment by hijkzzz** [comment]
> add basic ckpt function: [f53571d](https://github.com/OpenLLMAI/OpenRLHF/commit/f53571de43a4524644e75c9c472bbc69ac7b72c2)
> 
> I've added a basic checkpointing feature, which by default supports 3 checkpoints or a storage usage of up to 100GB. The logging, checkpointing, and evaluation functionalities have been decoupled from the training loop and moved to the manage_running_steps function. Thus, the current training loop has been largely simplified to mainly consist of the train_step and manage_running_steps components.

I think 100G is too small for PPO to have two 34B models

**Comment by catqaq** [comment]
> > add basic ckpt function: [f53571d](https://github.com/OpenLLMAI/OpenRLHF/commit/f53571de43a4524644e75c9c472bbc69ac7b72c2)
> > I've added a basic checkpointing feature, which by default supports 3 checkpoints or a storage usage of up to 100GB. The logging, checkpointing, and evaluation functionalities have been decoupled from the training loop and moved to the manage_running_steps function. Thus, the current training loop has been largely simplified to mainly consist of the train_step and manage_running_steps components.
> 
> I think 100G is too small for PPO to have two 34B models

Yes, larger models require more space to save both the model and the optimizer. One can consider adjusting flexibly based on the model size or leave the decision to the users, as it's essential to avoid overloading the hard drive.
