### ISSUE TITLE
Support top chinese language models

### ISSUE THREAD

**Issue by wuxibin89** [OpenLLMAI/OpenRLHF#116]

**Comment by catqaq** [comment]
List of planned models:
Baichuan2
Qwen

**Comment by catqaq** [comment]
Transformers officially supports Flash Attention 2, but it only covers models like Llama. Is it necessary for us to support Flash Attention 2 for other models?

**Comment by wuxibin89** [comment]
https://github.com/huggingface/transformers/issues/26350 Transformers community is adding support for more architecture.

**Comment by catqaq** [comment]
> List of expected supported models:
> 
> * GLM
> * Baichuan2
> * Qwen
> * InternLM

Done,  but requires further performance testing, and more model support is also welcome.

Data for test:

- SFT: alpaca+alpaca_cn
- RM: hh-rlhf
- PPO: alpaca-cleaned+full-hh-rlhf+oasst1_pairwise_rlhf_reward



| model                 | SFT  | RM   | PPO  | Notes |
| --------------------- | ---- | ---- | ---- | ----- |
| Baichuan2-7B-Chat     | 1h   | 4h   |      |       |
| chatglm2-6b           |      |      |      |       |
| Qwen-7B-Chat          |      |      |      |       |
| internlm-chat-7b-v1_1 |      |      |      |       |
|                       |      |      |      |       |

**Comment by catqaq** [comment]
> > List of expected supported models:
> > 
> > * GLM
> > * Baichuan2
> > * Qwen
> > * InternLM
> 
> Done, [e770404](https://github.com/OpenLLMAI/OpenRLHF/commit/e77040484190349c3a3c7bb29101f7fd6c08ee86) but requires further performance testing, and more model testing is also welcome.
> 
> Data for test:
> 
> * SFT: alpaca+alpaca_cn
> * RM: hh-rlhf
> * PPO: alpaca-cleaned+full-hh-rlhf+oasst1_pairwise_rlhf_reward
> 
> model	SFT	RM	PPO	Notes
> Baichuan2-7B-Chat	1h	4h	71h	
> chatglm2-6b				
> Qwen-7B-Chat				
> internlm-chat-7b-v1_1

more test please!

**Comment by pikaqqqqqq** [comment]
Qwen-14B needs to support:

1. Different model architectures
2. Qwen cannot add extra special tokens
3. Qwen lacks eos_token setting, causing errors during dataset processing
4. Qwen supports flash_attention, but the parameter passing method is different

**Comment by jovany-wang** [comment]
What's the progress?

**Comment by Triang-jyed-driung** [comment]
Add RWKV

Would you like implementing RLHF for RWKV, here are some suggestions:
1. As a non-transformer architecture, RWKV does not use the HF transformers library.
2. RWKV uses a different tokenizer, called `rwkv_vocab_v20230424`, and tokenization process is based on their own tokenizer.
3. The official repositories are https://github.com/BlinkDL/RWKV-LM and https://github.com/BlinkDL/ChatRWKV. See train.py for training process.
4. RWKV contains tons of new tricks and would fail if any of these tricks is not set correctly.

**Comment by catqaq** [comment]
> Add RWKV
> 
> Would you like implementing RLHF for RWKV, here are some suggestions:
> 
> 1. As a non-transformer architecture, RWKV does not use the HF transformers library.
> 2. RWKV uses a different tokenizer, called `rwkv_vocab_v20230424`, and tokenization process is based on their own tokenizer.
> 3. The official repositories are https://github.com/BlinkDL/RWKV-LM and https://github.com/BlinkDL/ChatRWKV. See train.py for training process.
> 4. RWKV contains tons of new tricks and would fail if any of these tricks is not set correctly.

It seems that it is not easy to be compatible with RWKV in OpenRLHF.

**Comment by ftmtk** [comment]
I am wondering if `mistral` has been supported?

**Comment by catqaq** [comment]
> I am wondering if `mistral` has been supported?

Not yet

**Comment by hijkzzz** [comment]
> I am wondering if `mistral` has been supported?

OpenRLHF supports mistral since it's model architecture is the same as llama2.

**Comment by wxhheian** [comment]
现在qwen支持了吗

**Comment by wxhheian** [comment]
我看qwen的 特殊token       <|endoftext|>  在代码里面没有体现？

**Comment by catqaq** [comment]
> 我看qwen的 特殊token <|endoftext|> 在代码里面没有体现？

应该是支持了，周末测测看~
