### ISSUE TITLE
DeepSpeed Training and Inference

### ISSUE THREAD

**Issue by ZiyiLiubird** [OpenLLMAI/OpenRLHF#139]
It seems that in your scripts, the locak_rank always equals -1, so actually you didn't use deepspeed's parallel ability? e.g., data parallel or model parallel

**Comment by hijkzzz** [comment]
This parameter is passed by DeepSpeed command tools,  i.e, `deepspeed xxxx.py`

**Comment by ZiyiLiubird** [comment]
Does OpenRLFH support ZeRO parallel + DDP inference? For example, I have 8 GPUs and each GPU loads a llama 13B model. So the data is divided into 8 batches to send 8 GPUs every time, and I gather all inference results from all GPUs. Furthermore, ZeRO supports larger batch inference.
