### ISSUE TITLE
问一下，huggingface提供的checkpoint为pt文件，如何转成大模型常见的.bin

### ISSUE THREAD

**Issue by zjintheroom** [OpenLLMAI/OpenRLHF#156]

**Comment by hijkzzz** [comment]
我们提供了 save_hf 的选项来保存为hf 的格式，不过这方面没有测试太多。至于转换成bin还没有研究过~有兴趣的话你可以hack代码直接用 hf 的 类函数保存模型

**Comment by catqaq** [comment]
@zjintheroom just use torch to load .pt  and save .bin

**Comment by zjintheroom** [comment]
> @zjintheroom just use torch to load .pt and save .bin

ok,i used the following code to load the weights
![Dingtalk_20231220160254](https://github.com/OpenLLMAI/OpenRLHF/assets/56460829/1153a68d-8d15-4fda-b1b5-487e2ee980b3)
 but in the end the program got the follow error.
 
![Dingtalk_20231220160402](https://github.com/OpenLLMAI/OpenRLHF/assets/56460829/017baed8-4df5-430f-b72d-8a0b1283ff2c)
the origin model is llama2-7b and the weight is the sft-ocra-500k_7b.pt。
Can you help me with this? thanks！

**Comment by catqaq** [comment]
related to pad token? you can refer to: https://github.com/OpenLLMAI/OpenRLHF/discussions/164
