### ISSUE TITLE
为什么速度回比deepspeed chat快4倍这么多

### ISSUE THREAD

**Issue by tingshua-yts** [OpenLLMAI/OpenRLHF#158]
看了下代码，没有领悟出来为什么会比dschat快4倍。
反而我觉得deepspeedchat可能会更快一点，因此deepspeedchat有hybrid engine，来对generate流程进行加速？

**Comment by hijkzzz** [comment]
rlhf 80% 的时间在generation
提升generation速度最快的方式是加大 batch_size =>显存需求暴增
假设你4个模型都是13b 用 deepspeed 的方式就必须用 zero3 速度可想而知
即使是 hybrid engine 的 TP 推理也干不过 直接 省显存加大batch size

补充：我们已经支持了vLLM 做推理加速 MR还没发出来 就在最近 到时候将会遥遥领先

**Comment by tingshua-yts** [comment]
“TP干不过加大batch size”这个感觉不一定啊。zero2使用4卡，batch size大到一定层度GPU sm已经跑满了，再加大也没有用了。如果用TP使用8k的话，反而能够使用更多的GPU sm。

**Comment by hijkzzz** [comment]
> “TP干不过加大batch size”这个感觉不一定啊。zero2使用4卡，batch size大到一定层度GPU sm已经跑满了，再加大也没有用了。如果用TP使用8k的话，反而能够使用更多的GPU sm。

实测 RLHF 中小模型 zero2 generation 一定是最快的，没有通信延迟/GEMM切分等任何其他开销，TP 就是为了应对大模型内存不够的。纸上谈兵没啥意义，自己拿台 DGXA100 跑一跑就知道哪个方便了那个快了，DSChat 的 hybrid engine 还是噱头成分比较大（你可以看看它用来展示 60B模型的时候 RM 只有 350m）。

**Comment by Jack47** [comment]
deepspeed 的优势在于节省卡数？因为它可以原地用同样数量的卡来做 tp 推理？
