### ISSUE TITLE
Support KTO

### ISSUE THREAD

**Issue by hijkzzz** [OpenLLMAI/OpenRLHF#161]
References:
https://github.com/ContextualAI/HALOs/blob/main/assets/report.pdf
https://github.com/ContextualAI/HALOs

**Comment by catqaq** [comment]
I suggest that we can create a special topic or discussion area for RLHF and other alignment technologies, and gradually provide support over time.

**Comment by hijkzzz** [comment]
https://github.com/OpenLLMAI/OpenRLHF/pull/201
