### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by zhanghaoie** [OpenLLMAI/OpenRLHF#171]
Hi, I have used the baichuan-13b model to run OpenRLHF with ray. but the memory consumption is very high after load all models. It needs 450G memory. Is this reasonable?

Memory on the node ( ID: 37f3bd9fa11d642c9e13892ee048dfc1f58c4597b77202a59a33835b) where the task (actor ID: 658f7608dec0f9a3428857d502000000, name=RewardModelRayActor.__init__, pid=5315, memory used=1.67GB) was running was 445.48GB / 468.75GB (0.950365), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: 384252cde217c088bb1cceb44ff7b1fec88a53bd8e7c82273275b694) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 33.123.202.4`. To see the logs of the worker, use `ray logs worker-384252cde217c088bb1cceb44ff7b1fec88a53bd8e7c82273275b694*out -ip 33.123.202.4. Top 10 memory users:
PID	MEM(GB)	COMMAND
5312	211.81	ray::ActorModelRayActor
5313	202.20	ray::CriticModelRayActor.init_model_from_pretrained
5315	1.67	ray::RewardModelRayActor
5314	1.66	ray::ReferenceModelRayActor
4396	0.30	python3 examples/train_ppo_ray.py --ref_num_nodes 1 --ref_num_gpus_per_node 1 --reward_num_nodes 1 -...
877	0.23	/root/.local/lib/python3.8/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/session_...
1183	0.09	/opt/conda/envs/python3.8.13/bin/python -u /root/.local/lib/python3.8/site-packages/ray/dashboard/ag...
184	0.08	/home/a/vipsrv-dns/vipsrv-dns -conf /home/a/vipsrv-dns/vipserver-coredns.cfg -dns.port 53
4312	0.06	ray::JobSupervisor

**Comment by hijkzzz** [comment]
If you use adam offload it does take up a lot of CPU memory

**Comment by zhanghaoie** [comment]
Hi, what's the configuration you have used to run 13B or 34B PPO. I have used 8 A800, 1 for reward model, 1 for reference model, 2 for critic model, 4 for actor model and zero-2. but CUDA run out of memory for 13B actor and critic.

**Comment by hijkzzz** [comment]
See https://github.com/OpenLLMAI/OpenRLHF/blob/main/examples/scripts/train_ppo_llama_ray_34b.sh

**Comment by zhanghaoie** [comment]
thank you very much for your reply

**Comment by wuxibin89** [comment]
> Hi, what's the configuration you have used to run 13B or 34B PPO. I have used 8 A800, 1 for reward model, 1 for reference model, 2 for critic model, 4 for actor model and zero-2. but CUDA run out of memory for 13B actor and critic.

@zhanghaoie If CUDA run out of memory, please enable `adam_offload` and `gradient_checkpointing`, and adjust `micro_train_batch_size` and `micro_rollout_batch_size`. For your setting, below configuration
- --micro_train_batch_size=8
- --micro_rollout_batch_size=16
- --adam_offload
- --gradient_checkpointing

should be OK.
