### ISSUE TITLE
Bug？

### ISSUE THREAD

**Issue by ZiyiLiubird** [OpenLLMAI/OpenRLHF#175]
https://github.com/OpenLLMAI/OpenRLHF/blob/bbfd171a6b72f770973d1a0c6f26d818e9b7742c/examples/train_sft.py#L68

https://github.com/OpenLLMAI/OpenRLHF/blob/bbfd171a6b72f770973d1a0c6f26d818e9b7742c/examples/train_sft.py#L89

https://github.com/OpenLLMAI/OpenRLHF/blob/bbfd171a6b72f770973d1a0c6f26d818e9b7742c/openrlhf/utils/deepspeed.py#L273

**Comment by wuxibin89** [comment]
@ZiyiLiubird Should be `exist_ok=True`, I will fix this.

**Comment by hijkzzz** [comment]
Fixed
