### ISSUE TITLE
[bug]: AttributeError: 'dict' object has no attribute 'mean'

### ISSUE THREAD

**Issue by eyuansu62** [OpenLLMAI/OpenRLHF#177]
In train_rm.py:
'''
save mean/std to config.json
model.config.mean = model.mean.item()
model.config.std = model.std.item()
'''
It seems that these two lines may cause the above bugs.
After prepare, the correct is model.module.

**Comment by hijkzzz** [comment]
Thanks we will fix it as soon as possible
