### ISSUE TITLE
Some weights of LLMForSequenceRegression were not initialized.

### ISSUE THREAD

**Issue by eyuansu62** [OpenLLMAI/OpenRLHF#180]
After saving my own trained rm model and using batch_inference to evaluate, it reports: Some weights of LLMForSequenceRegression were not initialized from the model checkpoint at ./ckpt/7b_llama and are newly initialized:...
Did I miss something?

**Comment by eyuansu62** [comment]
when I saved my own trained model, it reports that: Removed shared tensor,{xxx}.
Is it related to this error?

**Comment by hijkzzz** [comment]
Could you please share the error log with us? We recently modified the saving mechanism of the rm model, but did not test it adequately. thx

**Comment by eyuansu62** [comment]
lolll, it seems that only transformers==4.36.2 can save and load successfully. even 4.36.1 can cause this error.
