### ISSUE TITLE
reward数据准备的一个细节问题

### ISSUE THREAD

**Issue by tonylin52** [OpenLLMAI/OpenRLHF#194]
这个工程很棒！

有个问题是在准备rm模型训练数据时，prompt + chosen后面会加一个空格然后再加上`<eos>`：
`chosen = prompt + chosen + " " + self.tokenizer.eos_token`

请问这个空格是有什么考究吗？因为deepspeedchat里面没有加。

**Comment by hijkzzz** [comment]
早期 llama 的 tokenizer 有bug 导致不加空格识别不了 </s>
这些prompt格式可以自己改的 影响不大

**Comment by tonylin52** [comment]
> 早期 llama 的 tokenizer 有bug 导致不加空格识别不了 `</s>` 这些prompt格式可以自己改的 影响不大

收到 感谢
