### ISSUE TITLE
Bug: 'ActorModelRayActor' object has no attribute 'actor'

### ISSUE THREAD

**Issue by hmzo** [OpenLLMAI/OpenRLHF#195]
The reason seems to be that the reference occurs before the assignment in these two lines:

https://github.com/OpenLLMAI/OpenRLHF/blob/main/openrlhf/trainer/ray/ppo_actor.py#L194
https://github.com/OpenLLMAI/OpenRLHF/blob/main/openrlhf/trainer/ray/ppo_critic.py#L98

**Comment by wuxibin89** [comment]
Fixed https://github.com/OpenLLMAI/OpenRLHF/pull/197
