### ISSUE TITLE
error with saving checkoint with Mistral model 

### ISSUE THREAD

**Issue by karthik19967829** [OpenLLMAI/OpenRLHF#212]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2024-02-17_22-45-44_889855_91023/runtime_resources/working_dir_files/_ray_pkg_302ee178ac237502/openrlhf/trainer/ray/ppo_actor.py", line 319, in save_model
    self.strategy.save_model(
  File "/tmp/ray/session_2024-02-17_22-45-44_889855_91023/runtime_resources/working_dir_files/_ray_pkg_302ee178ac237502/openrlhf/utils/deepspeed.py", line 291, in save_model
    model_to_save.save_pretrained(output_dir, state_dict=output_state_dict, **kwargs)
  File "/tmp/ray/session_2024-02-17_22-45-44_889855_91023/runtime_resources/pip/e564889bd602f40c28eb7af52389ec2d70bacad1/virtualenv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2366, in save_pretrained
    model_to_save.generation_config.save_pretrained(save_directory)
  File "/tmp/ray/session_2024-02-17_22-45-44_889855_91023/runtime_resources/pip/e564889bd602f40c28eb7af52389ec2d70bacad1/virtualenv/lib/python3.11/site-packages/transformers/generation/configuration_utils.py", line 560, in save_pretrained
    raise ValueError(
ValueError: The generation config instance is invalid -- `.validate()` throws warnings and/or exceptions. Fix these issues to save the configuration.

Thrown during validation:
[UserWarning('`do_sample` is set to `False`. However, `temperature` is set to `0.5` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.')]

**Comment by hijkzzz** [comment]
@wuxibin89

**Comment by hijkzzz** [comment]
It works well without Ray and vLLM.

**Comment by karthik19967829** [comment]
while saving the checkpoint the error is raised

**Comment by wuxibin89** [comment]
According to 
https://github.com/huggingface/transformers/pull/28477
https://github.com/huggingface/transformers/blob/main/src/transformers/generation/configuration_utils.py#L400-L410
It seems like actor model's generation_config has been set with `do_sample=False` and `temperature=0.5`, transformers refuses to save generation_config. But Mistral's default generation_config is `do_sample=False` and `temperature=1.0`, and OpenRLHF doesn't change it. So we should verify your  default generation_config first.
```bash
>>> from transformers import AutoModelForCausalLM, BitsAndBytesConfig, PreTrainedModel
/root/miniconda3/lib/python3.9/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
>>> model = AutoModelForCausalLM.from_pretrained("mistralai/Mistral-7B-v0.1",trust_remote_code=True,attn_implementation = "flash_attention_2")
Downloading shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 228.13it/s]
You are attempting to use Flash Attention 2.0 without specifying a torch dtype. This might lead to unexpected behaviour
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes. No dtype was provided, you should run training or inference using Automatic Mixed-Precision via the `with torch.autocast(device_type='torch_device'):` decorator.
Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes. No dtype was provided, you should run training or inference using Automatic Mixed-Precision via the `with torch.autocast(device_type='torch_device'):` decorator.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:27<00:00, 43.58s/it]
>>> model.generation_config
GenerationConfig {
  "bos_token_id": 1,
  "eos_token_id": 2
}

>>> cfg = model.generation_config
>>> cfg.do_sample
False
>>> cfg.temperature
1.0
```

**Comment by karthik19967829** [comment]
great thanks , will check my setting and post the default config

**Comment by karthik19967829** [comment]
File "/root/miniconda3/envs/open-env/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 356, in from_engine_args
    engine = cls(*engine_configs,
             ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/open-env/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 111, in __init__
    self._init_workers()
  File "/root/miniconda3/envs/open-env/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 152, in _init_workers
    self._run_workers("load_model")
  File "/root/miniconda3/envs/open-env/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 983, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/open-env/lib/python3.11/site-packages/vllm/worker/worker.py", line 92, in load_model
    self.model_runner.load_model()
  File "/root/miniconda3/envs/open-env/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 75, in load_model
    self.model = get_model(self.model_config, self.lora_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/open-env/lib/python3.11/site-packages/vllm/model_executor/model_loader.py", line 88, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/root/miniconda3/envs/open-env/lib/python3.11/site-packages/vllm/model_executor/models/mistral.py", line 349, in load_weights
    param = params_dict[name]
            ~~~~~~~~~~~^^^^^^
KeyError: 'model.layers.0.self_attn.rotary_emb.cos_cached'

fixed the default config related issue and got the checkpoint , running it this when I try to test the saved model 

from vllm import LLM, SamplingParams

prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

model_path = "" 

llm = LLM(model="/openrlhf/examples/scripts/ckpt/mistral_7b")

outputs = llm.generate(prompts, sampling_params)

# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

**Comment by wuxibin89** [comment]
It seems like RoPE cache `model.layers.0.self_attn.rotary_emb.cos_cached` is saved in checkpoint, but vllm doesn't ignore it when load weights(vllm only ignore `rotary_emb.inv_freq` but `rotary_emb.cos_cached`).
https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/mistral.py#L357-L358
```python
        for name, loaded_weight in hf_model_weights_iterator(
                model_name_or_path, cache_dir, load_format, revision):
            if "rotary_emb.inv_freq" in name:
                continue
```

But according to 
https://github.com/huggingface/transformers/blob/main/src/transformers/models/mistral/modeling_mistral.py#L115-L116
```python
        self.register_buffer("cos_cached", emb.cos().to(dtype), persistent=False)
        self.register_buffer("sin_cached", emb.sin().to(dtype), persistent=False)
```
`cos_cached` and `sin_cached` are persistent=False and should not be saved. What's your transformers version?

**Comment by wuxibin89** [comment]
Fixed in https://github.com/OpenLLMAI/OpenRLHF/pull/213

**Comment by karthik19967829** [comment]
great thanks , testing it out

**Comment by karthik19967829** [comment]
Tested it out , works great thanks! we can close this issue
