### ISSUE TITLE
clarification on config std and mean calculation 

### ISSUE THREAD

**Issue by karthik-nexusflow** [OpenLLMAI/OpenRLHF#224]
Hi Team, 
    we would like to drop in our reward model and would like to how the following values were calculated and added to config ? was this calculated by running reward inference on entire train reward dataset ? 
    
```
if hasattr(config, "mean"):
                self.mean[0] = config.mean
                self.std[0] = config.std
```

**Comment by hijkzzz** [comment]
The mean and std are calculated using the testing data  of RM (during RM training stage)

**Comment by wuxibin89** [comment]
https://github.com/OpenLLMAI/OpenRLHF/blob/main/openrlhf/trainer/rm_trainer.py#L219-L226

**Comment by karthik-nexusflow** [comment]
Great thanks
