### ISSUE TITLE
vllm requirement problem

### ISSUE THREAD

**Issue by jiashenggu** [OpenLLMAI/OpenRLHF#227]
You mentioned that vllm is required for 70B models and vLLM-based RLHF.
But I just want to run train_ppo_llama_ray.sh. When I run this script, the error tells me to install vllm.
I commented out all the vllm's, not sure if that's appropriate.

**Comment by hijkzzz** [comment]
pip install vllm==0.3.2

**Comment by jiashenggu** [comment]
I just want to run .train_ppo_llama_ray.sh. After I commented out all the vllm's used in train_ppo_llama_ray.sh, it seems to work fine.
I think it is odd to add flash-attn to the requirements at the beginning if vllm is required for all PPO training with Ray since they conflict with each other.

**Comment by hijkzzz** [comment]
Yes, we may consider providing a pre-build container in the future

**Comment by hijkzzz** [comment]
related issue: https://github.com/vllm-project/vllm/pull/2804

**Comment by wuxibin89** [comment]
> I just want to run .train_ppo_llama_ray.sh. After I commented out all the vllm's used in train_ppo_llama_ray.sh, it seems to work fine. I think it is odd to add flash-attn to the requirements at the beginning if vllm is required for all PPO training with Ray since they conflict with each other.

@jiashenggu Hi, thanks for you feedback. I will vllm lazy imported since not all user need it.

**Comment by wuxibin89** [comment]
Fixed in https://github.com/OpenLLMAI/OpenRLHF/pull/229
