### ISSUE TITLE
When DPO Yi-34B Assertion `srcIndex < srcSelectDimSize` failed

### ISSUE THREAD

**Issue by victorShawFan** [OpenLLMAI/OpenRLHF#240]
when i use train_dpo_llama_34b.sh to dpo Yi-34B-Chat, there will be an "Array out of bounds" kind of problem
<img width="525" alt="企业微信截图_367fcfdf-f47b-464d-a470-62defe645e51" src="https://github.com/OpenLLMAI/OpenRLHF/assets/40328132/13aa69ed-9e39-4b15-9994-55e2874426ea">
<img width="728" alt="企业微信截图_8f07f54a-2332-4201-9b1a-d4b86101487a" src="https://github.com/OpenLLMAI/OpenRLHF/assets/40328132/1b5b5b24-cf43-4b4c-97a1-86087a27b7dd">
<img width="735" alt="企业微信截图_0d17d8f0-1969-44bb-8a13-8f50fc216840" src="https://github.com/OpenLLMAI/OpenRLHF/assets/40328132/f794c699-6ba4-4eec-ba75-f556b7dc595b">
i use huggingface Yi-34B-Chat ckpt and tokenizer
i didn't modify any code about tokenizers, please help

**Comment by hijkzzz** [comment]
Please set `use_fast=False` in the  openrlhf/utils/utils.py ` tokenizer = AutoTokenizer.from_pretrained(pretrain, trust_remote_code=True, **sp_tokens)`

**Comment by hijkzzz** [comment]
now you can use the option "--disable_fast_tokenizer" in train_dpo.py

**Comment by victorShawFan** [comment]
still don't work, same bug, what problem could that be?

**Comment by hijkzzz** [comment]
> still don't work, same bug, what problem could that be?

use "--disable_fast_tokenizer"

**Comment by hijkzzz** [comment]
It makes more sense to look at acc mean
