### ISSUE TITLE
this repo's hack of rope embedding accepts different input than transformers

### ISSUE THREAD

**Issue by babu111** [OpenLLMAI/OpenRLHF#252]
<img width="1256" alt="image" src="https://github.com/OpenLLMAI/OpenRLHF/assets/30493956/695570ac-f5c1-4f78-87da-2a74aed5f8e9">
this is the implementation of the transformer rope, notice that it has a position_ids input

your hack doesn't have this input, so position_ids is fed into seq_len

<img width="940" alt="image" src="https://github.com/OpenLLMAI/OpenRLHF/assets/30493956/05788932-d63d-4563-bc68-ed2bf7c9f06b">

**Comment by babu111** [comment]
also, using flash_attn==2.4.2 will result in the following error
ImportError: /share/miniconda3/envs/openrlhf/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

**Comment by hijkzzz** [comment]
we have removed the hack  of RoPE due to hf has fixed the RoPE accuracy bugs
for flash attention, please see: https://github.com/OpenLLMAI/OpenRLHF/issues/251

**Comment by babu111** [comment]
thank you for your reply!
