### ISSUE TITLE
Hardware requirement

### ISSUE THREAD

**Issue by ridiculouz** [OpenLLMAI/OpenRLHF#254]
Hello,
Thanks for the great project! 
I have a question about the minimal hardware requirement to run PPO on 7B models. Is it possible to run `train_ppo_llama.sh` or `train_ppo_llama_ray.sh` with 4 40G A100 (full fine-tuning/LoRA)?

**Comment by ridiculouz** [comment]
Seem likes PPO can be only run with Ray on 40G GPUs?

**Comment by wuxibin89** [comment]
For 7B full fine-tuning, 4*A100 40G should be enough, ref/reward/actor/critic=1:1:1:1, i.e 1 GPU for each model.

**Comment by hijkzzz** [comment]
you can also combine  the rm and init node, therefore we can use 2 gpus for the actor

**Comment by ridiculouz** [comment]
@hijkzzz Do you mean by placing rm and ref on the same gpu?

**Comment by hijkzzz** [comment]
> @hijkzzz Do you mean by placing rm and ref on the same gpu?

right

**Comment by ridiculouz** [comment]
Thank you all! I will try it out.

**Comment by linhaojia13** [comment]
@ridiculouz Hi, I'm also trying to train a 7B PPO model using 4*40G A100s. Could you share your optimized script with me?
