### ISSUE TITLE
debugging with ray

### ISSUE THREAD

**Issue by mickel-liu** [OpenLLMAI/OpenRLHF#258]
Hi guys, 

Not an issue strictly related to this repo, did you guys figure out that there is a better way to debug ray-related code other than using `ray debug` and pdb? Is there a way to connect `ray debug` to vscode? How do you guys debug this code normally? Setting ray `local_mode==true` could make use of the vscode debugger but it could only use a single gpu.

**Comment by wuxibin89** [comment]
Ray is a distributed framework, so its debug is not natural as normal python program. For now, I would suggest `ray debug` and add more logging to your program.

**Comment by mickel-liu** [comment]
thank you, I guess there is no better way to work with it.
