### ISSUE TITLE
Inconsistent python version dependency

### ISSUE THREAD

**Issue by snailrowen1337** [OpenLLMAI/OpenRLHF#268]
This file (https://github.com/OpenLLMAI/OpenRLHF/blob/74a8b735f1f6d1689391c1a6cb4bcca127268346/openrlhf/datasets/unpaired_preference_dataset.py#L192) writes type hints as "A | B" which is a feature which was introduced in python 3.10. (https://peps.python.org/pep-0604/). However, the setup file only lists python 3.8 as a dependency (https://github.com/OpenLLMAI/OpenRLHF/blob/74a8b735f1f6d1689391c1a6cb4bcca127268346/setup.py#L50). Thus, there is inconsistent python version dependency.

**Comment by hijkzzz** [comment]
Thank you for your suggestion, we have been tested in python 3.10.
