### ISSUE TITLE
Update NGC and vllm version.

### ISSUE THREAD

**Issue by THINK2TRY** [OpenLLMAI/OpenRLHF#282]
Thanks for the wonderful project! Does OpenRLHF support the use of the latest version of vllm and newer NGC (like 24.02), as vllm now is updated to v0.4.1 currently? Or what should I do to adapt OpenRLHF to them ?

**Comment by hijkzzz** [comment]
still work in progress

**Comment by hijkzzz** [comment]
Just try https://github.com/OpenLLMAI/OpenRLHF/pull/283
