### ISSUE TITLE
[question] long context for single model ppo training

### ISSUE THREAD

**Issue by yananchen1989** [OpenLLMAI/OpenRLHF#289]
hello. is it ok to ppo train 7b level models on single  gpu where each sample has around 6k length in prompt and round 2k length in completion ? 

any advice for this scenario ?  thanks

**Comment by hijkzzz** [comment]
A single GPU is not enough to run 7B + long text

**Comment by Freder-chen** [comment]
Hi @hijkzzz

I am trying to use `openrlhf.cli.train_ppo_ray` with multiple GPUs for training on long-context data. However, I noticed that it doesn't seem to implement Ring-Attention or similar memory-efficient techniques. This leads to out-of-memory (OOM) issues when processing long sequences. 

Could you clarify if there is a recommended way to handle such cases? 

Thank you for your time and guidance!
