### ISSUE TITLE
启用PPO Ray后无响应

### ISSUE THREAD

**Issue by victorShawFan** [OpenLLMAI/OpenRLHF#292]
使用ray start命令的反应：
<img width="727" alt="image" src="https://github.com/OpenLLMAI/OpenRLHF/assets/40328132/3450133f-9931-49a2-82ab-96b201d07f31">

运行train_ppo_llama.sh后的反应
<img width="744" alt="image" src="https://github.com/OpenLLMAI/OpenRLHF/assets/40328132/00da0080-6418-4c85-8acd-3a64047fc98c">

**Comment by victorShawFan** [comment]
<img width="739" alt="image" src="https://github.com/OpenLLMAI/OpenRLHF/assets/40328132/e5a178c2-77ce-462d-b9b6-b67fba1ab027">
脚本修改情况

**Comment by hijkzzz** [comment]
可能是 脚本目录下 文件太多 ray 一直在上传文件

**Comment by victorShawFan** [comment]
是这个问题，已解决 thanks
