### ISSUE TITLE
Claim your paper on HF

### ISSUE THREAD

**Issue by adeenayakup** [OpenLLMAI/OpenRLHF#299]
Hi, 
Congrats on OpenRLHF, it's really cool🔥 
The [paper](https://huggingface.co/papers/2405.11143)has been featured on our [Daily papers page ](https://huggingface.co/papers). It would be great to claim the paper by your HF account and engage with the community by sharing some insights in the discussion thread. : )

**Comment by openllmai0** [comment]
thx for attention~
