### ISSUE TITLE
train_ppo_llama_ray_70b.sh run two H800 machine  error

### ISSUE THREAD

**Issue by yangzhipeng1108** [OpenLLMAI/OpenRLHF#316]
![image](https://github.com/OpenLLMAI/OpenRLHF/assets/33448441/cc39717f-224b-44b9-8b32-7c9363c3ed73)
![image](https://github.com/OpenLLMAI/OpenRLHF/assets/33448441/96b61c3d-ae33-49fa-a21a-1b692a85f8bd)

**Comment by hijkzzz** [comment]
Is there an NCCL connection between the two machines (required by vLLM weights sync)
