### ISSUE TITLE
ray多节点训练下deepspeed zero3的切分还是按照 node数*8卡来切分吗？

### ISSUE THREAD

**Issue by lma-c4d** [OpenLLMAI/OpenRLHF#317]
看了这个ray actor初始化代码：
https://github.com/OpenLLMAI/OpenRLHF/blob/ea54281e818ebb084a10949a70d45341a009a8c5/openrlhf/trainer/ray/launcher.py#L158

有个疑问，按照这样写的话，deepspeed zero3的参数和优化器状态的切分是按照每个节点内切8份，还是能看到所有的node按照node数*8来切？

**Comment by hijkzzz** [comment]
你需要指定节点的数量的 仅在指定节点上运行
