### ISSUE TITLE
[Question] Is multi-nodes stage 3 model loading supported?

### ISSUE THREAD

**Issue by mickelliu** [OpenLLMAI/OpenRLHF#320]
I wish to try out stage 3 without Adam offloading, but I would imagine you would have to use multiple nodes to just hold the actor's weights, I have briefly tried to set the number of GPU per actor node to 16 but to no avail, so I assume this is not yet supported? And I wonder if this is technically feasible with the OpenRLHF ray-based framework so I can spend some time looking into it.

**Comment by hijkzzz** [comment]
please set node number to 2 and gpu per node to 8 and zero stage to 3 if you use the cluster like dgxa100

**Comment by mickelliu** [comment]
got it, will try it out, thank you!
