### ISSUE TITLE
Status message: Unexpected error occurred: The actor 2c5251641e72297b4e3f4d7f01000000 is unavailable

### ISSUE THREAD

**Issue by lusongshuo-mt** [OpenLLMAI/OpenRLHF#339]
使用多节点（3台8 * 80G A100）运行 train_ppo_ray.sh 经常会遇到以下问题，各节点环境配置一致
![1719838437456](https://github.com/OpenLLMAI/OpenRLHF/assets/127823925/d018a6bd-9243-430f-b2b2-beaf74b3437f)

**Comment by hijkzzz** [comment]
没遇到过这个问题，可以debug一下

**Comment by lusongshuo-mt** [comment]
ray start --head --node-ip-address 0.0.0.0 --num-gpus 8
换成主节点ip后解决： ray start --head --node-ip-address <ip_head_node> --num-gpus 8
