### ISSUE TITLE
Qwen-32B train RM using adam_offload& zero3 lead to Runtime Error

### ISSUE THREAD

**Issue by victorShawFan** [OpenLLMAI/OpenRLHF#343]
尝试训练Qwen-32B的RM，zero3起不来，尝试adam_offload，显示bug：
<img width="775" alt="image" src="https://github.com/OpenLLMAI/OpenRLHF/assets/40328132/710e414a-efc1-4aaa-8e99-693043f8c744">

训练脚本：
<img width="520" alt="image" src="https://github.com/OpenLLMAI/OpenRLHF/assets/40328132/a514b0b1-7602-4bf4-9200-3e7438cd7aa8">

**Comment by victorShawFan** [comment]
已在别处看到作者issue：https://github.com/microsoft/DeepSpeed/issues/5469
参考issue：https://github.com/microsoft/DeepSpeed/issues/5538
当前deepspeed版本正是v0.14.2正在尝试降低版本至0.14.0

**Comment by catqaq** [comment]
这个没有测试过，RM的训练一般没有那么耗资源。欢迎同步进展~
