### ISSUE TITLE
这个工程哪儿都好，就是数据读入咋搞的这么复杂，就不能sft和rl 分别以及 chat 模版，用一套简单的方式设定一下吗？

### ISSUE THREAD

**Issue by ldh127** [OpenLLMAI/OpenRLHF#347]
好好的工程，数据处理模块感觉可以适当调整下，希望作者能规范一下，和firefly 那样也可以啊，简单易用，不管是啥格式的数据，来了都给我处理成工程设定的格式，而不是让工程去迁就千奇百怪的数据。希望作者能修改一下，感谢！～

**Comment by catqaq** [comment]
这个问题之前讨论过，数据易用性需要一些人力支持，文档部分可能不够完善。目前可以对照Demo脚本里的主流数据格式进行准备即可，或者可以使用chat template特性。后续也会考虑约束一套格式及其文档说明。
最后，对于你提问中的不礼貌，我们提醒你注意，请遵守基本的社区礼仪。

**Comment by ldh127** [comment]
> 这个问题之前讨论过，数据易用性需要一些人力支持，文档部分可能不够完善。目前可以对照Demo脚本里的主流数据格式进行准备即可，或者可以使用chat template特性。后续也会考虑约束一套格式及其文档说明。 最后，对于你提问中的不礼貌，我们提醒你注意，请遵守基本的社区礼仪。

抱歉抱歉，工程别的代码都是非常优秀的，只是看到这么好的工程，第一次使用这个工程，感觉数据读入模块可以限定下自己的格式，可能可以降低第一次使用这个框架的使用成本，谢谢回复～～，我把这个问题删除了吧

**Comment by catqaq** [comment]
没事，留着吧，这个问题本身是有意义的。只是开发者有时不太会意识到数据格式约束是个紧迫的问题，但对于刚接触项目的同学来说确实会造成一些使用上的门槛。后续有时间会完善一下文档

**Comment by hijkzzz** [comment]
Hi 我们提供了文档 基本上就是套用 HuggingFace 的 ChatTemplate
其实很简单 可能你之前用的老版本
https://openrlhf.readthedocs.io/en/latest/quick_start.html#prepare-datasets

**Comment by ldh127** [comment]
> Hi 我们提供了文档 基本上就是套用 HuggingFace 的 ChatTemplate 其实很简单 可能你之前用的老版本~~ https://openrlhf.readthedocs.io/en/latest/quick_start.html#prepare-datasets

其实你们框架方面不需要考虑多种方法，只需要一种，然后别人来把数据弄成这个格式就可以了

**Comment by hijkzzz** [comment]
> > Hi 我们提供了文档 基本上就是套用 HuggingFace 的 ChatTemplate 其实很简单 可能你之前用的老版本~~ https://openrlhf.readthedocs.io/en/latest/quick_start.html#prepare-datasets
> 
> 其实你们框架方面不需要考虑多种方法，只需要一种，然后别人来把数据弄成这个格式就可以了

嗯嗯 后面可能会考虑 删除 --input_template 只保留 hf tokenizer 的 chat_template。

**Comment by hijkzzz** [comment]
> > > Hi 我们提供了文档 基本上就是套用 HuggingFace 的 ChatTemplate 其实很简单 可能你之前用的老版本~~ https://openrlhf.readthedocs.io/en/latest/quick_start.html#prepare-datasets
> > 
> > 
> > 其实你们框架方面不需要考虑多种方法，只需要一种，然后别人来把数据弄成这个格式就可以了
> 
> 嗯嗯 后面可能会考虑 删除 --input_template 只保留 hf tokenizer 的 chat_template 以及完全自定义的数据集。

目前应该非常干净了 https://github.com/OpenLLMAI/OpenRLHF/blob/main/openrlhf/datasets/sft_dataset.py

**Comment by ldh127** [comment]
> > > > Hi 我们提供了文档 基本上就是套用 HuggingFace 的 ChatTemplate 其实很简单 可能你之前用的老版本~~ https://openrlhf.readthedocs.io/en/latest/quick_start.html#prepare-datasets
> > > 
> > > 
> > > 其实你们框架方面不需要考虑多种方法，只需要一种，然后别人来把数据弄成这个格式就可以了
> > 
> > 
> > 嗯嗯 后面可能会考虑 删除 --input_template 只保留 hf tokenizer 的 chat_template 以及完全自定义的数据集。
> 
> 目前应该非常干净了 https://github.com/OpenLLMAI/OpenRLHF/blob/main/openrlhf/datasets/sft_dataset.py

能对sft,dpo,ppo,kto 分别弄几条样例数据吗。就像现在的代码，我看这个地方，
if apply_chat_template:
        prompt = apply_chat_template(data[input_key][:-1], tokenize=False, add_generation_prompt=True)
        response = apply_chat_template(data[input_key], tokenize=False)[len(prompt) :]
我就不知道为啥 data[input_key][:-1] 的 data[input_key] 不是一个 str 吗，怎么还要 取倒数最后一个，以及 apply_chat_template 怎么能够自定义 qwen 或则 别的其他的模型的模板呢？
感谢回复，感谢付出的精力～

**Comment by hijkzzz** [comment]
> > > > > Hi 我们提供了文档 基本上就是套用 HuggingFace 的 ChatTemplate 其实很简单 可能你之前用的老版本~~ https://openrlhf.readthedocs.io/en/latest/quick_start.html#prepare-datasets
> > > > 
> > > > 
> > > > 其实你们框架方面不需要考虑多种方法，只需要一种，然后别人来把数据弄成这个格式就可以了
> > > 
> > > 
> > > 嗯嗯 后面可能会考虑 删除 --input_template 只保留 hf tokenizer 的 chat_template 以及完全自定义的数据集。
> > 
> > 
> > 目前应该非常干净了 https://github.com/OpenLLMAI/OpenRLHF/blob/main/openrlhf/datasets/sft_dataset.py
> 
> 能对sft,dpo,ppo,kto 分别弄几条样例数据吗。就像现在的代码，我看这个地方， if apply_chat_template: prompt = apply_chat_template(data[input_key][:-1], tokenize=False, add_generation_prompt=True) response = apply_chat_template(data[input_key], tokenize=False)[len(prompt) :] 我就不知道为啥 data[input_key][:-1] 的 data[input_key] 不是一个 str 吗，怎么还要 取倒数最后一个，以及 apply_chat_template 怎么能够自定义 qwen 或则 别的其他的模型的模板呢？ 感谢回复，感谢付出的精力～

这个就是 HF 的标准格式，应该是通用的， 你可以去看我们的样例 数据集呀，比如 https://huggingface.co/datasets/OpenLLMAI/preference_dataset_mixture2_and_safe_pku

**Comment by hijkzzz** [comment]
> > > > > Hi 我们提供了文档 基本上就是套用 HuggingFace 的 ChatTemplate 其实很简单 可能你之前用的老版本~~ https://openrlhf.readthedocs.io/en/latest/quick_start.html#prepare-datasets
> > > > 
> > > > 
> > > > 其实你们框架方面不需要考虑多种方法，只需要一种，然后别人来把数据弄成这个格式就可以了
> > > 
> > > 
> > > 嗯嗯 后面可能会考虑 删除 --input_template 只保留 hf tokenizer 的 chat_template 以及完全自定义的数据集。
> > 
> > 
> > 目前应该非常干净了 https://github.com/OpenLLMAI/OpenRLHF/blob/main/openrlhf/datasets/sft_dataset.py
> 
> 能对sft,dpo,ppo,kto 分别弄几条样例数据吗。就像现在的代码，我看这个地方， if apply_chat_template: prompt = apply_chat_template(data[input_key][:-1], tokenize=False, add_generation_prompt=True) response = apply_chat_template(data[input_key], tokenize=False)[len(prompt) :] 我就不知道为啥 data[input_key][:-1] 的 data[input_key] 不是一个 str 吗，怎么还要 取倒数最后一个，以及 apply_chat_template 怎么能够自定义 qwen 或则 别的其他的模型的模板呢？ 感谢回复，感谢付出的精力～

也可以参考 
![image](https://github.com/OpenLLMAI/OpenRLHF/assets/19810594/90c1cf80-a7f6-45f2-8ba4-3e6f03e3a6f7)
