### ISSUE TITLE
Why is the RM head separately initialized?

### ISSUE THREAD

**Issue by ZhaofengWu** [OpenLLMAI/OpenRLHF#348]
Thanks for the great library! I noticed that when creating a RM, the regression head is separately initialized. Why is that needed, instead of just defaulting to pytorch's initialization?

https://github.com/OpenLLMAI/OpenRLHF/blob/e3f5e2b1ef8b59de6e95602e5c7840b13d8aa79d/openrlhf/models/model.py#L154-L161

**Comment by hijkzzz** [comment]
Make the final reward mean close to 0

**Comment by ZhaofengWu** [comment]
I see, thanks! So if I want to train a RM using pointwise data (in a regression setup; rather than pairwise data), I should disable this, right? Since I do want the reward to be non-zero.

**Comment by hijkzzz** [comment]
> I see, thanks! So if I want to train a RM using pointwise data (in a regression setup; rather than pairwise data), I should disable this, right? Since I do want the reward to be non-zero.

For DeepSpeed ZeRO3, you should enable it or just modify it. (The automatic initialization of PyTorch will be invalid.)

**Comment by ZhaofengWu** [comment]
Oh, ok, so essentially it's always good to have `init_value_head=True`. And if I don't want the reward to be close to 0, I should just copy PyTorch's default initialization scheme to this place, i.e. `init.kaiming_uniform_(model.value_head.weight, a=math.sqrt(5))`. Is that right?

**Comment by ZhaofengWu** [comment]
Or I guess alternatively, simply `model.value_head.reset_parameters()`?

**Comment by hijkzzz** [comment]
> Oh, ok, so essentially it's always good to have `init_value_head=True`. And if I don't want the reward to be close to 0, I should just copy PyTorch's default initialization scheme to this place, i.e. `init.kaiming_uniform_(model.value_head.weight, a=math.sqrt(5))`. Is that right?

Yes

**Comment by ZhaofengWu** [comment]
Thank you!
