### ISSUE TITLE
process groups for actor and vllm engine

### ISSUE THREAD

**Issue by babu111** [OpenLLMAI/OpenRLHF#357]
I'm trying to modify OpenRLHF's code for a academic project. During careful inspection of OpenRLHF's ppo code, I find that you first allocate gpus to actors using ray options, then assign all vllm engines to actors with rank 0 for process group init. I wonder why is the code organized like this? I tried to make vllm engines parallel to actors, as opposed to the current subsidiary relationship, but failed. I'd appreciate it if the authors can clarify what happens when ray is used on top of deepspeed and pytorch.

**Comment by hijkzzz** [comment]
We build an NCCL group between rank 0 of the Actors and vLLM engines.
