### ISSUE TITLE
SFT loss calculation issue

### ISSUE THREAD

**Issue by ZhaofengWu** [OpenLLMAI/OpenRLHF#362]
Usually in SFT/LM loss calculation, the labels are left-shifted by one position because each position predicts the **next** token, e.g. https://github.com/huggingface/transformers/blob/6fbea6d237cbdfc3c229cdadfa3c968cfb2d5142/src/transformers/models/llama/modeling_llama.py#L1093-L1102. However this is not done in `sft_trainer.py`. Is that correct?

**Comment by hijkzzz** [comment]
this is done in gpt loss

**Comment by ZhaofengWu** [comment]
Ahh ok, thanks!
